version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9080:9080"
    volumes:
      - .:/app
    command: bash -c "python manage.py runserver 0.0.0.0:8000 & scrapyrt -p 9080 -i 0.0.0.0"
